RSS_FEED_LINKS = {
    'Finn.no': 'http://tech.finn.no/atom.xml',
    'Flickr': 'https://code.flickr.net/feed/',
    'Freeletics': 'https://freeletics.engineering/feed.xml',
    'Galois': 'https://galois.com/feed/',
    'GameChanger': 'http://tech.gc.com/atom.xml',
    'GIPHY': 'https://engineering.giphy.com/rss',
    'GitHub': 'https://github.blog/engineering.atom',
    'GitHub Old': 'https://github.blog/feed/',
    'GoCardless': 'https://gocardless.com/content-platform/rss/resources.xml',
    'GoDaddy': 'https://www.godaddy.com/engineering/feed.xml',
    'GoSquared': 'https://www.gosquared.com/blog/feed',
    'Grab': 'http://engineering.grab.com/feed.xml',
    'Grofers': 'https://lambda.blinkit.com/feed',
    'Groupon': 'https://medium.com/feed/groupon-eng',
    'Guardian': 'https://www.theguardian.com/info/developer-blog/rss',
    'Gusto': 'https://engineering.gusto.com/rss/',
    'HackerEarth': 'http://engineering.hackerearth.com/rss',
    'Haptik': 'https://www.haptik.ai/tech/rss.xml',
    "Harry's": 'https://medium.com/feed/harrys-engineering',
    'Hashnode': 'https://engineering.hashnode.com/rss.xml',
    'Hashrocket': 'https://hashrocket.com/blog.rss',
    'Helpshift': 'https://medium.com/feed/helpshift-engineering',
    'Heroku': 'https://blog.heroku.com/engineering',
    'HomeAway': 'https://medium.com/feed/expedia-group-tech',
    'Honeybadger': 'http://blog.honeybadger.io/blog/feed.xml',
    'Hootsuite': 'https://medium.com/feed/hootsuite-engineering',
    'Hostinger': 'https://www.hostinger.com/blog/feed',
    'Housing.com': 'https://medium.com/feed/engineering-housing',
    'HubSpot': 'https://product.hubspot.com/blog/rss.xml',
    'IMVU': 'https://engineering.imvu.com/?feed=rss2',
    'Indeed': 'https://engineering.indeedblog.com/feed/',
    'Instacart': 'https://tech.instacart.com/feed',
    'Instagram': 'https://instagram-engineering.com/feed',
    'Jane Street': 'https://blogs.janestreet.com/feed.xml',
    'Jobandtalent': 'https://jobandtalent.engineering/feed',
    'JobTeaser': 'https://medium.com/feed/jobteaser-dev-team',
    'Just Eat': 'https://tech.justeattakeaway.com/feed/',
    'Khan Academy': 'http://engineering.khanacademy.org/rss',
    'Kinvolk': 'https://kinvolk.io/blog/index.xml',
    'Kogan.com': 'https://devblog.kogan.com/blog?format=rss',
    'Kolosek': 'https://kolosek.com/blog/rss/',
    'LINE': 'https://engineering.linecorp.com/en/blog',
    'LiveRamp': 'https://liveramp.com/wp-json/wp/v2/pages/1041448',
    'Localytics': 'https://eng.localytics.com/rss/',
    'Lyft': 'https://eng.lyft.com/feed',
    'Made Tech': 'https://www.madetech.com/feed/podcast/',
    'MapTiler': 'https://www.maptiler.com/news/feed/posts.xml',
    'Medium': 'https://medium.engineering/feed',
    'Mesosphere': 'https://d2iq.com/feed',
    'Microsoft Python Engineering': 'https://devblogs.microsoft.com/python/feed/',
    'Moove-it': 'https://blog.moove-it.com/rss',
    'Mozilla Automation Team': 'https://planet.mozilla.org/automation/atom.xml',
    'Mozilla Hacks': 'https://hacks.mozilla.org/feed/',
    'Mozilla Release Engineering': 'https://planet.mozilla.org/releng/atom.xml',
    'Netflix': 'https://netflixtechblog.com/feed',
    'New York Times': 'https://open.nytimes.com/feed',
    'Nextdoor': 'https://engblog.nextdoor.com/feed',
    'Nordic APIs': 'https://nordicapis.com/feed/',
    'Novoda': 'https://www.novoda.com/blog/rss',
    'NPR Apps': 'https://blog.apps.npr.org/atom.xml',
    'Nvidia': 'https://blogs.nvidia.com/feed/',
    'OCTO Technology': 'https://blog.octo.com/feed',
    'Okta': 'https://developer.okta.com/feed.xml',
    'OLX': 'https://tech.olx.com/feed',
    'OpenDNS': 'https://umbrella.cisco.com/feed',
    'Oursky': 'https://code.oursky.com/feed/',
    'Palantir': 'https://blog.palantir.com/feed',
    'Panorama Education': 'https://medium.com/feed/building-panorama-education',
    'Paypal': 'https://medium.com/feed/paypal-tech',
    'PicCollage': 'https://tech.pic-collage.com/feed',
    'Pinterest': 'https://medium.com/feed/@Pinterest_Engineering',
    'Postman': 'https://medium.com/feed/better-practices',
    'Postmark': 'https://postmarkapp.com/blog/feed.atom',
    'Prezi': 'https://engineering.prezi.com/feed',
    'PubNub:': 'https://www.pubnub.com/feed/blog/',
    'PullReview': 'http://blog.8thcolor.com/atom.xml',
    'REA Group': 'https://www.rea-group.com/category/tech/feed/',
    'Remind': 'http://engineering.remind.com/feed.xml',
    'RetailMeNot': 'https://engineering.ziffmedia.com/feed',
    'Riot Games': 'https://technology.riotgames.com/rss.xml',
    'RisingStack': 'https://blog.risingstack.com/feed/',
    'RoseHosting': 'https://www.rosehosting.com/blog/feed/',
    'Schibsted Tech Polska': 'https://www.schibsted.pl/wp-json/wp/v2/pages/3339',
    'Sensible': 'https://blog.sensible.io/rss',
    'Serverless': 'https://www.serverless.com/blog/rss.xml',
    'Sharethis': 'https://www.sharethis.com/platform/social-feed/',
    'Shopify': 'https://shopify.engineering/blog.atom',
    'SitePoint': 'https://sitepoint.com/sitepoint.rss',
    'Sky Betting & Gaming': 'https://sbg.technology/feed.xml',
    'Skyscanner': 'https://medium.com/feed/@SkyscannerEng',
    'Slack': 'https://slack.engineering/rss',
    'Small Improvements': 'https://tech.small-improvements.com/rss',
    'Soshace': 'https://soshace.com/feed/',
    'Soundcloud': 'https://developers.soundcloud.com/blog/blog.rss',
    'Speedledger': 'http://engineering.speedledger.com/feed/',
    'Spotify': 'https://engineering.atspotify.com/feed',
    'Sqreen': 'https://www.datadoghq.com/product/application-security-management/index.xml',
    'Square': 'https://corner.squareup.com/blog/rss.xml',
    'Squarespace': 'https://engineering.squarespace.com/blog?format=rss',
    'Stack Overflow': 'https://stackoverflow.blog/feed',
    'Stackshare': 'https://stackshare.io/featured-posts.atom',
    'Stitch Fix': 'https://multithreaded.stitchfix.com/feed.xml',
    'Strava': 'https://medium.com/feed/strava-engineering',
    'Stripe': 'https://stripe.com/blog/feed.rss',
    'SurveyMonkey': 'https://www.surveymonkey.com/feed/',
    'Swiggy': 'https://bytes.swiggy.com/feed',
    'Takipi': 'http://blog.takipi.com/rss',
    'Target': 'https://target.github.io/feed.xml',
    'Teamwork': 'https://engineroom.teamwork.com/feed',
    'theScore': 'http://techblog.thescore.com/feed.xml',
    'Thoughtbot': 'https://feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots',
    'Thumbtack': 'https://medium.com/feed/thumbtack-engineering',
    'Timescale': 'https://www.timescale.com/blog/rss/',
    'Tinder': 'https://medium.com/feed/tinder',
    'Toptal': 'https://www.toptal.com/blog.rss',
    'Transferwise': 'https://medium.com/feed/wise-engineering',
    'Trivago': 'http://tech.trivago.com/rss.xml',
    'TrueCar': 'https://medium.com/feed/driven-by-code',
    'Tumblr': 'https://engineering.tumblr.com/rss',
    'Twilio': 'https://www.twilio.com/blog/feed',
    'Universe': 'https://engineering.universe.com/feed',
    'UpGrad': 'https://engineering.upgrad.com/feed',
    'Vena Solutions': 'https://engineering.vena.io/feed/',
    'VersionEye': 'https://blog.versioneye.com/feed/',
    'Vinted': 'https://vinted.engineering//atom.xml',
    'VNGRS': 'https://medium.com/feed/vngrs',
    'VTS': 'https://buildingvts.com/feed',
    'Wayfair': 'https://www.aboutwayfair.com/careers/tech-blog.rss',
    'Wealthfront': 'https://eng.wealthfront.com/feed/',
    'Wemake.services': 'https://medium.com/feed/wemake-services',
    'Wingify': 'http://engineering.wingify.com/atom.xml',
    'WyeWorks': 'https://wyeworks.com/rss.xml',
    'XING': 'https://tech.new-work.se/feed',
    'Yahoo': 'https://yahooeng.tumblr.com/rss',
    'Yammer': 'https://medium.com/feed/yammer-engineering',
    'Zendesk': 'https://zendesk.engineering/feed',
    'Zendesk(old)': 'https://developerblog.zendesk.com/feed',
    '0xADADA': 'https://0xadada.pub/rss.xml',
    'Aaron Patterson': 'http://tenderlovemaking.com/atom.xml',
    'Abu Ashraf Masnun': 'https://masnun.com/feed',
    'Addy Osmani': 'http://addyosmani.com/rss.xml',
    'Alan Storm': 'https://alanastorm.com/feed/feed.xml',
    'Alex Russell': 'https://infrequently.org/feed/',
    'Amit Merchant': 'https://www.amitmerchant.com/feed.xml',
    'Anders Aarvik': 'http://aarvik.dk/rss/index.html',
    'Andrew Bancroft': 'https://www.andrewcbancroft.com/index.xml',
    'Antirez': 'http://antirez.com/rss',
    'Ariejan de Vroom': 'https://www.devroom.io/index.xml',
    'Ariya Hidayat': 'https://ariya.io/index.xml',
    'Armin Ronacher': 'http://lucumr.pocoo.org/feed.atom',
    'Axel Rauschmayer': 'https://2ality.com/feeds/posts.atom',
    'Bad Concurrency': 'http://bad-concurrency.blogspot.com/feeds/posts/default',
    'Bartlomiej Filipek': 'https://www.cppstories.com/index.xml',
    'Bill the Lizard': 'https://www.billthelizard.com/feed/',
    'Bjørn Johansen': 'https://www.bjornjohansen.com/feed',
    'Blake Erickson': 'https://blog.blakeerickson.com/feed.xml',
    "Blundell's Android Tutorials": 'https://blog.blundellapps.co.uk/feed/',
    'Bohops': 'https://bohops.com/feed/',
    'Brendan Eich': 'https://brendaneich.com/feed/',
    'Brendan Gregg': 'http://www.brendangregg.com/blog/rss.xml',
    'Brujo Benavides': 'https://medium.com/feed/@elbrujohalcon',
    'Bryan Cantrill': 'https://bcantrill.dtrace.org/feed/',
    'Carlos Becker': 'https://carlosbecker.com/index.xml',
    'Chen Hui Jing': 'https://www.chenhuijing.com/feed.xml',
    'Chien Tran': 'https://thelazylog.com/rss/',
    'Chris Wellons': 'http://nullprogram.com/feed/',
    'Code with style!': 'https://codewithstyle.info/atom.xml',
    'Codrops': 'https://tympanus.net/codrops/feed/',
    'Daily JS': 'https://medium.com/feed/dailyjs',
    'Daily Tech Video': 'https://dailytechvideo.com/feed/',
    'Dan Luu': 'https://danluu.com/atom.xml',
    'Daniel Doubrovkine (dB.)': 'https://code.dblock.org/feed.xml',
    'Daniel Schmidt': 'https://medium.com/feed/@dschmidt1992',
    'Dave Cheney': 'https://dave.cheney.net/feed',
    'David Walsh': 'https://davidwalsh.name/feed/atom',
    'Dean Hume': 'https://deanhume.com/rss/',
    'Dennis Felsing': 'https://hookrace.net/blog/feed/',
    'Dereuromark': 'https://www.dereuromark.de/feed/',
    'Domenico Luciani': 'https://domenicoluciani.com/feed.xml',
    'Dot Dev (.dev)': 'https://dotdev.co/feed/',
    'Dragan Djuric': 'https://dragan.rocks/feed.xml',
    'Dragan Gaic': 'http://www.gajotres.net/feed/',
    'Drew DeVault': 'https://drewdevault.com/blog/index.xml',
    'Eddie Smith': 'http://www.practicallyefficient.com/feed.xml',
    'Edgar Aroutiounian': 'https://hyegar.com/index.xml',
    'Edward Faulkner': 'https://eaf4.com/rss/',
    'Elegant Code': 'https://elegantcode.com/feed/',
    'Eli Bendersky': 'https://eli.thegreenplace.net/feeds/all.atom.xml',
    'Eric Elliot': 'https://medium.com/feed/javascript-scene',
    'Eric Lippert': 'https://ericlippert.com/feed/',
    'Erik Runyon': 'https://erikrunyon.com/feed.xml',
    'Evan Hahn': 'https://evanhahn.com/blog/index.xml',
    'Evan Jones': 'http://www.evanjones.ca/index.rss',
    'Evan Miller': 'http://www.evanmiller.org/news.xml',
    'Federico Cargnelutti': 'https://blog.fedecarg.com/feed/',
    'Federico Tomassetti': 'https://tomassetti.me/wp-json/wp/v2/pages/6218',
    'Filippo Valsorda': 'https://words.filippo.io/rss/',
    'Freek Van der Herten': 'https://freek.dev/feed',
    'Gleb Bahmutov': 'https://glebbahmutov.com/blog/atom.xml',
    'Graham King': 'https://www.darkcoding.net/index.xml',
    'Guido van Rossum': 'http://neopythonic.blogspot.com/feeds/posts/default',
    'Guilherme Rodrigues': 'https://firstdoit.com/feed',
    'Hayden James': 'https://haydenjames.io/feed',
    'Henrik Lau Eriksson': 'https://conductofcode.io/feed.xml',
    'Henrik Warne': 'https://henrikwarne.com/feed/',
    'High Scalability': 'https://highscalability.com/rss/',
    'Huon Wilson': 'http://huonw.github.io/blog/atom.xml',
    'Hypriot': 'https://blog.hypriot.com/index.xml',
    'Ian Hummel': 'https://themodernlife.github.io/feed.xml',
    "Idontgetoutmuch's Weblog": 'https://idontgetoutmuch.wordpress.com/feed/',
    'Ievgen Kuzminov': 'http://stdout.in/en/cat/all.rss',
    'Ilija Eftimov': 'http://ieftimov.com/index.xml',
    'Ilya Grigorik': 'https://ilya.grigorik.com/essays/rss/',
    'Itamar Turner-Trauring': 'https://codewithoutrules.com/atom.xml',
    'Jacopo Tarantino': 'https://jack.ofspades.com/rss/index.html',
    'Jake Trent': 'https://jaketrent.com/post/feed.xml',
    'Jake Wharton': 'https://jakewharton.com/atom.xml',
    'Jake Yesbeck': 'http://jakeyesbeck.com/atom.xml',
    'James Hague': 'http://prog21.dadgum.com/atom.xml',
    'James Long': 'https://archive.jlongster.com/atom.xml',
    'Jamis Buck': 'http://feeds.feedburner.com/buckblog',
    'Jan Lelis': 'https://idiosyncratic-ruby.com/feed.xml',
    'Jay Fields': 'http://blog.jayfields.com/feeds/posts/default',
    'Jeff Atwood': 'https://blog.codinghorror.com/rss/',
    'Jeff Preshing': 'http://preshing.com/feed',
    'Jeremy Kun': 'https://www.jeremykun.com/index.xml',
    'Jerry Gamblin': 'https://jerrygamblin.com/feed/',
    'Jesal Gadhia': 'https://jes.al/atom.xml',
    'Jessie Frazelle': 'https://blog.jessfraz.com/index.xml',
    'Joe Nelson': 'https://begriffs.com/atom.xml',
    'Joel Spolsky': 'https://www.joelonsoftware.com/feed/',
    'Johannes Brodwall': 'http://johannesbrodwall.com/index.xml',
    'John Resig': 'https://feeds.feedburner.com/JohnResig',
    'John Wittenauer': 'https://www.johnwittenauer.net/rss/',
    'Jon Skeet': 'https://codeblog.jonskeet.uk/feed/',
    'Jonathan Dekhtiar': 'http://www.born2data.com/feed_atom.xml',
    'Jonathan Snook': 'https://snook.ca/jonathan/index.rdf',
    'Josh Haberman': 'https://blog.reverberate.org/feed.xml',
    'Josh Sherman': 'https://joshtronic.com/feed/',
    'Juan Treminio': 'https://jtreminio.com/feed',
    'Julia Evans': 'https://jvns.ca/atom.xml',
    'Junior Grossi': 'https://blog.jgrossi.com/feed/',
    'Justin Weiss': 'https://www.justinweiss.com/atom.xml',
    'K. Harrison': 'https://useyourloaf.com/blog/rss.xml',
    'Kevin Burke': 'https://kevin.burke.dev/feed/',
    'Kirill Shevchenko': 'https://medium.com/feed/@kirill_shevch',
    'Kyle Kingsbury': 'https://aphyr.com/posts.atom',
    'Lambda the Ultimate': 'http://lambda-the-ultimate.org/rss.xml',
    'Larry Land': 'https://lg.io/feed.xml',
    'Lazarus Lazaridis': 'https://iridakos.com/feed.xml',
    'Lea Verou': 'http://lea.verou.me/feed.xml',
    'Lerner Consulting Blog': 'http://blog.lerner.co.il/feed',
    'Life Plus Linux': 'http://lifepluslinux.blogspot.com/feeds/posts/default',
    'Luciano Mammino': 'https://loige.co/rss.xml',
    'Marc Plano-Lesay': 'https://enoent.fr/index.xml',
    'Marcelo Rinesi': 'https://blog.rinesi.com/feed/',
    'Marco Pivetta': 'https://ocramius.github.io/atom.xml',
    'Marek Majkowski': 'https://idea.popcount.org/rss.xml',
    'Mark Seaborn': 'http://lackingrhoticity.blogspot.com/feeds/posts/default',
    'Martin Fowler': 'https://martinfowler.com/feed.atom',
    'Mary Rose Cook': 'https://maryrosecook.com/blog/feed.xml',
    'Matt Aimonetti': 'https://matt.aimonetti.net/posts/index.xml',
    'Matt Cutts': 'https://www.mattcutts.com/blog/feed/',
    'Matt Might': 'http://matt.might.net/articles/feed.rss',
    'Matt Warren': 'http://mattwarren.org/atom.xml',
    'Matthew Green': 'https://blog.cryptographyengineering.com/feed/',
    'Michael Crump': 'https://www.michaelcrump.net/feed.xml',
    'Michael Herman': 'https://mherman.org/feed.xml',
    'Miguel Quinones': 'https://www.miqu.me/atom.xml',
    'Mike Ash': 'http://www.mikeash.com/pyblog/rss.py',
    'Mike Fogus': 'http://blog.fogus.me/feed/',
    'Miro Cupak': 'https://mirocupak.com/feed.xml',
    'Monica Dinculescu': 'https://meowni.ca/atom.xml',
    'Monstermuffin': 'https://blog.monstermuffin.org/index.xml',
    'Mykhailo Kozik': 'http://feeds.feedburner.com/mishadoff',
    'Nelson Elhage': 'https://blog.nelhage.com/atom.xml',
    'Nic Raboy': 'https://www.thepolyglotdeveloper.com/blog/index.xml',
    'Nick Craver': 'https://nickcraver.com/blog/feed.xml',
    'Nick Desaulniers': 'https://nickdesaulniers.github.io/index.xml',
    'Nicolas Liochon': 'http://blog.thislongrun.com/feeds/posts/default',
    'Nicolai Parlog (CodeFX)': 'http://codefx.org/feed.xml',
    'Nikola Brežnjak': 'https://nikola-breznjak.com/blog/feed/atom/',
    'NSHipster': 'http://nshipster.com/feed.xml',
    'Nate Berkopec': 'https://www.nateberkopec.com/feed.xml',
    'Ofer Zelig': 'https://fullstack.info/feed/',
    'Ole Begemann': 'https://oleb.net/blog/atom.xml',
    'Oona Räisänen': 'https://www.windytan.com/feeds/posts/default',
    'Pamela Fox': 'http://blog.pamelafox.org/feeds/posts/default',
    'Pat Shaughnessy': 'http://feeds2.feedburner.com/patshaughnessy',
    'Paul Irish': 'https://feeds.feedburner.com/paul-irish',
    'Paul Lewis': 'https://aerotwist.com/blog/feed/',
    'Paweł Chudzik': 'https://blog.pchudzik.com/index.xml',
    'Peter Norvig': 'http://www.norvig.com/rss-feed.xml',
    'Peter Steinberger': 'http://petersteinberger.com/atom.xml',
    'Peteris Krumins': 'https://catonmat.net/feed',
    'Petr Mitrichev': 'https://blog.mitrichev.ch/feeds/posts/default',
    'Philip Walton': 'https://feeds.feedburner.com/philipwalton',
    'Philipp Oppermann': 'https://os.phil-opp.com/rss.xml',
    'Pony Foo': 'https://feeds.feedburner.com/ponyfoo',
    'Piotr Pasich': 'http://piotrpasich.com/feed/',
    'Rachel Kroll': 'https://rachelbythebay.com/w/atom.xml',
    'Radek Pazdera': 'http://radek.io/rss',
    'Radim Řehůřek': 'https://radimrehurek.com/feed/',
    'Ramon Fried': 'https://nativeguru.wordpress.com/feed/',
    'Ray Wenderlich': 'https://www.raywenderlich.com/feed',
    'Raymond Chen': 'https://devblogs.microsoft.com/oldnewthing/feed',
    'Raymond Hettinger': 'https://rhettinger.wordpress.com/feed/',
    'ReactJS News': 'https://reactjsnews.com/feed.xml',
    'Real Python': 'https://realpython.com/atom.xml',
    'Reginald Braithwaite': 'https://raganwald.com/atom.xml',
    'Regular Geek': 'https://regulargeek.com/feed/',
    'Rob Allen': 'https://akrabat.com/feed/',
    'Robert C. Martin': 'http://blog.cleancoder.com/atom.xml',
    'Robin Ward': 'https://eviltrout.com/feed.xml',
    'Robin Wilson': 'https://blog.rtwilson.com/feed/',
    'Ruslan Spivak': 'https://ruslanspivak.com/feeds/all.atom.xml',
    'Sam Saffron': 'http://samsaffron.com/posts.rss',
    'Schakko': 'https://www.schakko.de/feed/',
    'Scott Hanselman': 'http://feeds.hanselman.com/ScottHanselman',
    'Scott Johnson': 'http://fuzzyblog.io/blog/feed.xml',
    'Srinivas Tamada': 'https://www.9lessons.info/feeds/posts/default',
    'Stack Abuse': 'https://stackabuse.com/rss/',
    'Stanko Tadić': 'https://muffinman.io/atom.xml',
    'Stefan Parker': 'https://codebeforethehorse.tumblr.com/rss',
    'Stephen Colebourne': 'https://blog.joda.org/feeds/posts/default',
    'Steve Bellovin': 'https://www.cs.columbia.edu/~smb/blog/control/blog.xml',
    'Steve Yegge': 'https://steve-yegge.blogspot.com/feeds/posts/default',
    'Swizec Teller': 'https://swizec.com/rss.xml',
    'Tania Rascia': 'https://tania.dev/rss.xml',
    'The Coded Self': 'https://www.thecodedself.com/feed.xml',
    'The Daily WTF': 'https://syndication.thedailywtf.com/TheDailyWtf',
    'Thomas Young': 'http://upcoder.com/feed',
    'Tikhon Jelvis': 'http://jelv.is/blog/rss.xml',
    'T.J. Maher': 'https://www.tjmaher.com/feeds/posts/default',
    'Una Kravets': 'https://una.im/rss.xml',
    'Undocumented Matlab': 'https://undocumentedmatlab.com/feed',
    'Vanilla Java': 'http://blog.vanillajava.blog/feeds/posts/default',
    'Vlad Mihalcea': 'https://vladmihalcea.com/feed/',
    'Wilfred Hughes': 'http://www.wilfred.me.uk/rss.xml',
    'William Kennedy': 'https://www.goinggo.net/blog/index.xml',
    'Wojtek Gawroński': 'http://www.afronski.pl/feed.xml',
    'Yegor Bugayenko': 'https://www.yegor256.com/rss.xml',
    'Yifan Lu': 'http://yifan.lu/feed.xml',
    'Zach Holman': 'https://zachholman.com/atom.xml',
    'Zolmeister': 'https://zolmeister.com/feeds/posts/default',
    'Android': 'https://android-developers.googleblog.com/feeds/posts/default',
    'Bootstrap.com': 'https://blog.getbootstrap.com/feed.xml',
    'Crystal': 'https://crystal-lang.org/feed.xml',
    'Go': 'https://blog.golang.org/blog/feed.atom',
    'IPFS': 'https://blog.ipfs.tech/index.xml',
    'jOOQ': 'https://blog.jooq.org/feed/',
    'Kotlin': 'https://blog.jetbrains.com/kotlin/feed/',
    'Laravel': 'https://feed.laravel-news.com/',
    'Microsoft Edge': 'https://blogs.windows.com/msedgedev/wp-json/wp/v2/pages/24431',
    '.NET': 'https://devblogs.microsoft.com/dotnet/feed/',
    'React Native': 'http://facebook.github.io/blog/rss.xml',
    'Red': 'https://www.red-lang.org/feeds/posts/default',
    'RocksDB': 'http://rocksdb.org/feed.xml',
    'Rust': 'https://blog.rust-lang.org/feed.xml',
    'Sketch': 'https://blog.sketchapp.com/blog/feed.xml',
    'Swift': 'https://developer.apple.com/swift/blog/news.rss'
}